// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/jerry-yt-chen/event-sourcing-poc/internal/framework/router"
	"github.com/jerry-yt-chen/event-sourcing-poc/internal/injector/api"
	"github.com/jerry-yt-chen/event-sourcing-poc/internal/injector/lib"
	"github.com/jerry-yt-chen/event-sourcing-poc/internal/injector/persistence"
	"github.com/jerry-yt-chen/event-sourcing-poc/internal/receiver/user"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	service := persistence.InitMongo()
	publisher := lib.InitEventPublisher(service)
	receiver := user.ProvideReceiver(publisher)
	v := api.ProvideReceiverList(receiver)
	ginRouter := router.ProvideRouteV1(v...)
	httpEngine := api.InitGinEngine(ginRouter)
	injector := &Injector{
		HttpEngine: httpEngine,
	}
	return injector, func() {
	}, nil
}
